name = input('Enter your name: ')
up = name.upper()
print(f'The upper name is {up}')
lower = name.lower()
print(f'The lower name is {lower}')
how_many_letter = len(name.replace(" ", ""))
print(f'The name has {how_many_letter}')
first_name = len(name.split()[0])
print(f'The first name has {first_name}')